name: Insurance AI CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train ML model
      run: |
        python ml/train_model.py

    - name: Build Docker image
      run: |
        docker build -t insurance-ai .

    - name: Run container (smoke test)
      run: |
        docker run -d -p 5000:5000 insurance-ai
